"use client";

import { AnalysisResult } from "@/lib/types";

interface Props {
  result: AnalysisResult;
  isLatest?: boolean;
}

export default function ResultCard({ result, isLatest = false }: Props) {
  const date = new Date(result.timestamp).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  return (
    <div
      className={`rounded-2xl border overflow-hidden transition-all duration-300 ${
        isLatest
          ? "border-[#00d4ff]/30 bg-gradient-to-b from-[#00d4ff08] to-[#111827] shadow-lg shadow-[#00d4ff08]"
          : "border-[#1e3a5f] bg-[#111827]"
      }`}
    >
      {/* Card header */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-[#1e3a5f]/60">
        <div className="flex items-center gap-2">
          {isLatest && (
            <span className="flex h-2 w-2">
              <span className="relative inline-flex rounded-full h-2 w-2 bg-[#10b981]" />
            </span>
          )}
          <span
            className="text-xs font-semibold text-[#94a3b8] uppercase tracking-wider"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            {isLatest ? "Latest Analysis" : "Previous Analysis"}
          </span>
        </div>
        <span className="text-xs text-[#4b6280]">{date}</span>
      </div>

      <div className="p-5 space-y-5">
        {/* Summary section */}
        <div>
          <div className="flex items-center gap-2 mb-3">
            <div className="w-5 h-5 rounded-md bg-[#00d4ff]/10 border border-[#00d4ff]/20 flex items-center justify-center flex-shrink-0">
              <svg
                width="10"
                height="10"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#00d4ff"
                strokeWidth="2.5"
              >
                <path d="M4 6h16M4 10h16M4 14h10" />
              </svg>
            </div>
            <h3
              className="text-xs font-bold text-[#00d4ff] uppercase tracking-widest"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              AI Summary
            </h3>
          </div>
          <p className="text-[#e2e8f0] text-sm leading-relaxed bg-[#0d1729]/60 rounded-xl p-4 border border-[#1e3a5f]/40">
            {result.summary}
          </p>
        </div>

        {/* Keywords section */}
        {result.keywords.length > 0 && (
          <div>
            <div className="flex items-center gap-2 mb-3">
              <div className="w-5 h-5 rounded-md bg-[#7c3aed]/10 border border-[#7c3aed]/20 flex items-center justify-center flex-shrink-0">
                <svg
                  width="10"
                  height="10"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#7c3aed"
                  strokeWidth="2.5"
                >
                  <path d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A2 2 0 013 12V7a4 4 0 014-4z" />
                </svg>
              </div>
              <h3
                className="text-xs font-bold text-[#7c3aed] uppercase tracking-widest"
                style={{ fontFamily: "var(--font-mono)" }}
              >
                Health Terms Detected ({result.keywords.length})
              </h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {result.keywords.map((kw) => (
                <span
                  key={kw}
                  className="inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-medium border"
                  style={{
                    background: "rgba(124, 58, 237, 0.06)",
                    borderColor: "rgba(124, 58, 237, 0.2)",
                    color: "#a78bfa",
                    fontFamily: "var(--font-mono)",
                  }}
                >
                  {kw}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Caution disclaimer */}
        <div className="flex items-start gap-3 p-3 rounded-xl border border-amber-500/20 bg-amber-500/5">
          <svg
            className="w-4 h-4 text-amber-400 mt-0.5 flex-shrink-0"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
            <line x1="12" y1="9" x2="12" y2="13" />
            <line x1="12" y1="17" x2="12.01" y2="17" />
          </svg>
          <p className="text-xs text-amber-300/80 leading-relaxed">
            <strong className="text-amber-400">Not a medical diagnosis.</strong>{" "}
            This analysis is generated by AI for educational purposes only.
            Always consult a qualified healthcare professional for medical
            advice, diagnosis, or treatment.
          </p>
        </div>

        {/* Input preview (collapsed) */}
        <details className="group">
          <summary className="cursor-pointer text-xs text-[#4b6280] hover:text-[#94a3b8] transition-colors list-none flex items-center gap-1">
            <svg
              className="w-3 h-3 transition-transform group-open:rotate-90"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path d="M9 18l6-6-6-6" />
            </svg>
            View input text
          </summary>
          <p className="mt-2 text-xs text-[#4b6280] leading-relaxed bg-[#0d1729]/40 rounded-lg p-3 border border-[#1e3a5f]/30 line-clamp-4">
            {result.inputText}
          </p>
        </details>
      </div>
    </div>
  );
}
